### ISSUE TITLE
Docker 部署 Confluence

### ISSUE THREAD

**Issue by slowlog** [slowlog/slowlog.github.io#20]
## docker-compose.yml
```
version: '2'
services:
  confluence:
    container_name: confluence
    image: cptactionhank/atlassian-confluence:5.10.6    
    ports:
      - "8090:8090"
    restart: always
#网关要与 mysql 保持一致
networks:
  default:
    external:
      name: internal
volumes:
  confluence-data:
    driver: local
```
## 相关命令
- 删除挂载目录
`docker rm -v confluence-data`
## 参考
```
http://blog.sina.com.cn/s/blog_71d3c0040102v8y7.html
http://wuyijun.cn/shi-yong-dockerfang-shi-an-zhuang-he-yun-xing-confluence/
http://sunxboy.iteye.com/blog/2179038
```
